DIRECT BIT 20H.0
RUN	BIT 20H.1
V0	EQU 30H
V1	EQU 31H
V2	EQU 32H
LV0 EQU 33H		;个位
LV1 EQU 34H		;十位
LV2 EQU 35H		;百位
WV	EQU	36H		;循环位
START BIT P3.2	;启停
K1	BIT P3.0	;模式设定
K2	BIT P3.1	;左移
K4	BIT P3.3	;右移
K5	BIT P3.4	;增加
K6	BIT P3.5	;减小
K7	BIT P3.6
K8	BIT P3.7	

ORG 0000H
LJMP MAIN
ORG 0003H
LJMP INTR0
ORG 001BH
LJMP T1INTR
ORG 0100H
MAIN:	SETB P0.0		;固定电机不动
		CLR DIRECT		;初始位设置为0，正转
		CLR RUN			;初始不转
		MOV P3,#0FFH
		MOV V2,#00H
		MOV V1,#06H
		MOV V0,#00H
		MOV LV2,#00H
		MOV LV1,#06H
		MOV LV0,#00H
		MOV WV,#60H		;初始为3的倍数
		SETB IE0		;中断INT0下降沿触发方式
		SETB EX0		;中断允许
		SETB EA			;开中断
SETDIR:	MOV C,K1		;设置模式
		JB C,SETDIR2	;消抖
		LCALL DEL1K
		MOV C,K1
		JNB C,SETV
SETDIR2:MOV C,K5		;设置正反转
		JB C,SETDIR3
		LCALL DEL1K
		MOV C,K5
		JNB C,DIR
SETDIR3:MOV C,K6		;设置正反转
		JB C,SETDIR
		LCALL DEL1K
		MOV C,K6
		JNB C,DIR
		LJMP SETDIR
SETV:	MOV C,K1		;设置模式
		JB C,SETV2	;消抖
		LCALL DEL1K
		MOV C,K1
		JNB C,SETDIR
SETV2:	MOV C,K2		;设置左移
		JB C,SETV3
		LCALL DEL1K
		MOV C,K2
		JB C,SETV3
		INC WV
SETV3:	MOV C,K4		;设置右移
		JB C,SETV4
		LCALL DEL1K
		MOV C,K4
		JB C,SETV4
		DEC WV
SETV4:	MOV C,K5		;设置加
		JB C,SETV5
		LCALL DEL1K
		MOV C,K5
		JB C,SETV5
		MOV B,#03H
		MOV A,WV
		DIV AB
INC1:	JNZ B,INC2		;判断个位
		INC LV0
		AJMP SETV5
INC2:	DEC B			;判断十位
		JNZ B,INC3
		INC LV1
		AJMP SETV5
INC3:	INC LV2			;判断百位
SETV5:	MOV C,K6		;设置减
		JB C,SETV
		LCALL DEL1K
		MOV C,K6
		JB C,SETV
		MOV B,#03H
		MOV A,WV
		DIV AB
DEC1:	JNZ B,DEC2		;判断个位
		DEC LV0
		LJMP SETV
DEC2:	DEC B			;判断十位
		JNZ B,DEC3
		DEC LV1
		LJMP SETV
DEC3:	DEC LV2			;判断百位	
		LJMP SETV


DIR:	CPL DIRECT
		RET
		



		SETB P0.0
		ACALL DELAY
		CLR P0.0
		SETB P0.1
		ACALL DELAY
		CLR P0.1
		SETB P0.2
		ACALL DELAY
		CLR P0.2
		SETB P0.3
		ACALL DELAY
		CLR P0.3
		SJMP MAIN
DEL1K:	MOV R0,#200
DEL1K1:	MOV R1,#250
DEL1K2:	DJNZ R1,DEL1K2
		DJNZ R0,DEL1K1
		RET
DELAY:	MOV R0,#0FH
DEL1:	MOV R1,#03FH
DEL2:	DJNZ R1,DEL2
		DJNZ R0,DEL1
		RET
END
